
[general]
import = ["/home/dawid/Documents/dotfiles/alacritty/theme.toml"]

[window]
dynamic_padding = true
opacity = 0.9
decorations = "none"

[font]
normal.family = "Fira code medium"

[keyboard]
bindings = [{ key = "Tab", mods = "Alt", action = "SpawnNewInstance" }]
