[theme]
 name = "native"
# file = "/home/dawid/.config/i3status-rust/tokyo-night.toml"

[icons]
name = "material-nf"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "music"
buttons = ["play", "next"]
interface_name_exclude = [".*kdeconnect.*"]
hide_when_empty = true


[[block]]
block = "custom"
command = "/home/dawid/.config/i3status-rust/numlock_status"
interval = 0.5

[[block]]
block = "sound"
max_vol = 100

[[block]]
block = "time"
interval = 1
# format = "%a %d/%m %T :: %s"
format = "%H:%M"

