[theme]
theme = "native"
# file = "/home/dawid/.config/i3status-rust/tokyo-night.toml"

[icons]
icons = "material-nf"

[[block]]
block = "focused_window"
# max_w = 50
# marks = "visible"

[[block]]
block = "music"
format = "{$combo.str(max_w:20) $play $next |}"
interface_name_exclude = [".*kdeconnect.*", "mpd"]
# hide_when_empty = true



[[block]]
block = "custom"
command = "/home/dawid/.config/i3status-rust/numlock_status"
interval = 0.5
hide_when_empty = true

[[block]]
block = "sound"
max_vol = 100
[[block.click]]
button = "left"
action = "toggle_mute"


[[block]]
block = "time"
interval = 1
# format = "%a %d/%m %T :: %s"
format = " $timestamp.datetime(f:'%T') "
