theme = "native"
icons = "material-nf"

[[block]]
block = "focused_window"
max_width = 50
show_marks = "visible"

[[block]]
block = "music"
buttons = ["play", "next"]
interface_name_exclude = [".*kdeconnect.*", "mpd"]
hide_when_empty = true

[[block]]
block = "backlight"
device = "amdgpu_bl0"

[[block]]
block = "custom"
command = "/home/dawid/.config/i3status-rust/numlock_status"
interval = 0.5

[[block]]
block = "sound"
max_vol = 100

[[block]]
block = "time"
interval = 1
# format = "%a %d/%m %T :: %s"
format = "%s"

[[block]]
block = "battery"
interval = 10
format = "{percentage}"
# format_alt = "{time}"
if_command = "test -e /sys/class/power_supply/BAT0"



