[theme]
theme = "native"

[icons]
icons = "material-nf"

[[block]]
block = "focused_window"
# max_w = 50
# marks = "visible"

[[block]]
block = "music"
format = "$icon {$combo.str(max_w:20) $play $next |}"
interface_name_exclude = [".*kdeconnect.*", "mpd"]
# hide_when_empty = true

[[block]]
block = "backlight"
device = "amdgpu_bl0"

[[block]]
block = "custom"
command = "/home/dawid/.config/i3status-rust/numlock_status"
interval = 0.5
hide_when_empty = true

[[block]]
block = "sound"
max_vol = 100
[[block.click]]
button = "left"
action = "toggle_mute"

[[block]]
block = "time"
interval = 1
[block.format]
full = " $timestamp.datetime(f:%s)"
short = " $timestamp.datetime(f:'%a %d/%m %T :: %s') "


[[block]]
block = "battery"
interval = 10
full_format = "$icon"
format = "$icon $percentage"
# format_alt = "{time}"
if_command = "test -e /sys/class/power_supply/BAT0"



