anchor_to_edges = false
# icon_theme = 'Paper'
position = 'top'
height = 5

[[end]]
type = 'clock'

[[start]]
all_monitors = false
type = 'workspaces'

 [start.name_map]
 1 = '1'
 2 = '2'
 3 = '3'
 4 = '4'
 5 = '5'
 6 = '6'
 7 = '7'
 8 = '8'
 9 = '9'
 10 = '10'
