# icon_theme = 'Paper'
position = 'top'
height = 5

[[start]]
type = 'clock'
format = "%s"

[[end]]
name = "numlock"
type = "label"
label = "{{250: /home/dawid/.config/ironbar/scripts/numlock_azathoth.sh}}"


[[end]]
name = "battery"
type = "label"
label = "{{60000: /home/dawid/.config/ironbar/scripts/battery.sh}}"


[[end]]
name = "volume"
type = "label"
label = "{{250: /home/dawid/.config/ironbar/scripts/getVol.sh}}"

[[center]]
all_monitors = false
type = 'workspaces'

[start.name_map]
1 = '1'
2 = '2'
3 = '3'
4 = '4'
5 = '5'
6 = '6'
7 = '7'
8 = '8'
9 = '9'
10 = '10'
