"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = "[>](bold green)"
error_symbol = "[x](bold red)"
vicmd_symbol = "[<](bold green)"

[git_commit]
tag_symbol = " tag "

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[cmd_duration]
show_milliseconds = true



[c]
symbol = "C "

[cmake]
symbol = "cmake "

[directory]
read_only = " root"

[docker_context]
symbol = "docker "

[git_branch]
symbol = "git "

[golang]
symbol = "go "

[hg_branch]
symbol = "hg "

[java]
symbol = "java "

[lua]
symbol = "lua "

[nodejs]
symbol = "nodejs "

[memory_usage]
symbol = "memory "

[nim]
symbol = "nim "

[nix_shell]
symbol = "nix "

[ocaml]
symbol = "ml "

[package]
symbol = "pkg "

[perl]
symbol = "pl "

[php]
symbol = "php "

[python]
symbol = "py "

[rust]
symbol = "rs "

[sudo]
symbol = "sudo "
disabled = false
