idle_bg = "#1a1b26"
idle_fg = "#c0caf5"
info_bg = "#7aa2f7"
info_fg = "#414868"
good_bg = "#9ece6a"
good_fg = "#15161E"
warning_bg = "#e0af68"
warning_fg = "#15161E"
critical_bg = "#1a1b26"
critical_fg = "#f7768e"
separator = "|"
separator_bg = "auto"
separator_fg = "auto"
